# Synchornize with go requirements
# https://github.com/conda-forge/go-feedstock/blob/main/recipe/conda_build_config.yaml
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
