# Synchornize with go requirements
# https://github.com/conda-forge/go-feedstock/blob/main/recipe/conda_build_config.yaml
c_stdlib_version:          # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

MACOSX_SDK_VERSION:  # [osx]
  - 15.5             # [osx]
