# Synchornize with go requirements
# https://github.com/conda-forge/go-feedstock/blob/main/recipe/conda_build_config.yaml
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

# Save the size of our build matrix.
# Build with older protobuf upon request
# https://github.com/conda-forge/libprotobuf-feedstock/issues/198
# hmaarrfk - 2024/03 - requested to have builds for linux64
# 4.25.2 is the latest protobuf migration as of 2024/03/11
# 4.24.4 is the version that tensorflow 2.15 was last built with
libprotobuf:  # [linux64]
- '4.25.2'    # [linux64]
- '4.24.4'    # [linux64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
