{% set version = "7.9.1" %}
{% set zaber_bson_commit = "db11c31b2c1b69151648bb82150144f0b2003f29" %}

# Workaround needed as of 2025/01/22
# https://github.com/conda-forge/conda-smithy/pull/2227
{% if python_min is undefined %}
{% set python_min = "3.9" %}
{% endif %}

package:
  name: zaber-motion-split
  version: {{ version }}

source:
  - url: https://gitlab.com/zaber-core-libs/zaber-motion-lib/-/archive/v{{ version }}/zaber-motion-lib-v{{ version }}.tar.gz
    sha256: abc37743d127900a0f10349fd1d48b012fc6f2127ff0cbbe4a1cac0abc4351ea
    folder: src/zaber-motion
    patches:
      - patches/0001-Do-not-install-bindings-the-way-tey-do-upstream.patch
      - patches/0002-Do-not-download-bindings-during-setup.patch
  # url to the github archive at a particular commit
  - url: https://github.com/zabertech/bson/archive/{{ zaber_bson_commit }}.tar.gz
    sha256: e97301964ea85bb1dfed6872287e83c8de58730bd2c1393105f73a3875c960bf
    folder: bson

build:
  number: 0

outputs:
  - name: libzaber-motion
    script: build_lib.sh  # [unix]
    script: bld_lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libzaber-motion', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('cgo') }}
        - {{ compiler('m2w64_c') }}    # [win]
        - {{ stdlib('m2w64_c') }}      # [win]
        - {{ compiler('c') }}          # [not win]
        - {{ stdlib('c') }}            # [not win]
      host:
      run:

    test:
      commands:
        - test -f ${PREFIX}/lib/zaber-motion-lib${SHLIB_EXT}  # [unix]

  - name: zaber-motion
    script: build_python.sh  # [unix]
    script: bld_python.bat  # [win]
    build:
      noarch: python
      skip: true  # [not linux64]

    requirements:
      build:
        - python {{ python_min }}                # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        # For bson installation
        - pdm-backend
      run:
        - python >={{ python_min }}
        # https://gitlab.com/ZaberTech/zaber-motion-lib/-/blob/master/py/pyproject.toml?ref_type=heads#L13
        # But lets loosen thing just a tiny bit
        - reactivex 4.0.*
        - {{ pin_subpackage('libzaber-motion', max_pin='x.x.x') }}

    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - zaber_motion

about:
  home: https://gitlab.com/zaber-core-libs/zaber-motion-lib
  license: MIT
  license_family: MIT
  license_file:
    - src/zaber-motion/LICENSE
    - LICENSE_GO_MODULES
  summary: A Python library used to operate Zaber devices.
  doc_url: https://www.zaber.com/software/docs/motion-library/
  dev_url: https://gitlab.com/zaber-core-libs/zaber-motion-lib

extra:
  recipe-maintainers:
    - hmaarrfk
